Repository BookJamm/BE-express, pull requests merged in 2023-08, with the labels that each got.

#97 Feat: 96 update users, records
  src/records/recordsController.js
  src/records/recordsDao.js
  src/records/recordsProvider.js
  src/records/recordsRouter.js
  src/users/usersController.js
  src/users/usersDao.js
  src/users/usersProvider.js
  src/users/usersRouter.js
Labels: ✨ Feature, 🔧 Update

#95 GET /auth/refresh Access Token 재발급
  config/baseResponeStatus.js
  config/jwt.js
  config/middlewares.js
  src/auth/authController.js
  src/auth/authDao.js
  src/auth/authProvider.js
  src/auth/authRouter.js
Labels: ✨ Feature

#105 Feat: 104 books apis
  config/baseResponeStatus.js
  config/express.js
  package.json
  src/books/booksController.js
  src/books/booksProvider.js
  src/books/booksRouter.js
  src/records/recordsDao.js
Labels: ✨ Feature

#116 !HOTFIX: authDao 중복 코드 삭제
  src/auth/authDao.js
Labels: 🐛 Bug

#126 feat: 활동에 좋아요 있는지 표시
  src/activities/activitiesController.js
  src/activities/activitiesDao.js
  src/activities/activitiesProvider.js
Labels: 🔧 Update

#121 !HOTFIX!: 토큰 검증 로직 수정
  src/auth/authController.js
  src/auth/authProvider.js
Labels: 🐛 Bug

#107 Feature/106 search users
  src/users/usersController.js
  src/users/usersDao.js
  src/users/usersProvider.js
  src/users/usersRouter.js
  src/users/usersService.js
Labels: ✨ Feature

#114 활동 좋아요 및 활동 좋아요 취소
  config/baseResponeStatus.js
  src/activities/activitiesController.js
  src/activities/activitiesDao.js
  src/activities/activitiesProvider.js
  src/activities/activitiesRouter.js
  src/activities/activitiesService.js
Labels: ✨ Feature

#125 장소 검색 시 사진도 응답하도록 수정
  src/places/placesDao.js
  src/places/placesService.js
Labels: ✨ Feature

#129 feat: /places/:placeId/books response data update
  src/books/booksController.js
  src/books/booksProvider.js
  src/books/booksRouter.js
  src/places/placesDao.js
  src/places/placesService.js
Labels: ✨ Feature

#135 Fix/book and activities
  src/books/booksProvider.js
  src/places/placesService.js
  src/users/usersDao.js
Labels: 🐛 Bug, ✨ Feature

#132 update: place activities 보여 주는 api 카멜케이스 맞춤
  src/places/placesDao.js
Labels: 🔧 Update

#131 Feat/#130 response refactor
  src/auth/authController.js
  src/auth/authDao.js
  src/places/placesDao.js
Labels: 🔧 Update

#136 fix: recordsDao fix
  src/records/recordsController.js
  src/records/recordsDao.js
  src/records/recordsProvider.js
Labels: 🐛 Bug

#137 feat: POST /places/:placeId/bookmarks
  config/baseResponeStatus.js
  src/places/placesController.js
  src/places/placesDao.js
  src/places/placesRouter.js
  src/places/placesService.js
Labels: ✨ Feature
