Repository BookJamm/BE-express, pull requests merged in 2023-07, with the labels that each got.

#5 feature/3- get /records/:userId
  config/baseResponeStatus.js
  config/express.js
  src/records/recordsController.js
  src/records/recordsDao.js
  src/records/recordsProvider.js
  src/records/recordsRouter.js
  src/records/recordsService.js
Labels: enhancement

#19 Feat:18 GET friends records
  config/baseResponeStatus.js
  src/records/recordsController.js
  src/records/recordsDao.js
  src/records/recordsRouter.js
  src/records/recordsService.js
Labels: enhancement

#16 Feat: 장소 아이디를 입력받았을 때 해당 장소에 대한 활동 다 보여 주는 기능 구현
  src/Activity/activityController.js
  src/Activity/activityDao.js
  src/Activity/activityProvider.js
  src/Activity/activityRoute.js
Labels: enhancement

#15 Feature/13 delete review
  config/baseResponeStatus.js
  config/express.js
  src/places/placesService.js
  src/reviews/reviewsController.js
  src/reviews/reviewsDao.js
  src/reviews/reviewsProvider.js
  src/reviews/reviewsRouter.js
  src/reviews/reviewsService.js
Labels: enhancement

#27 Feat: 24 - POST /user apis
  config/express.js
  package.json
  src/records/recordsController.js
  src/records/recordsDao.js
  src/records/recordsProvider.js
  src/user/userController.js
  src/user/userDao.js
  src/user/userProvider.js
  src/user/userRouter.js
  src/user/userService.js
Labels: enhancement

#37 Feature/32 publish review
  config/middleware.js
  config/middlewares.js
  config/s3.js
  package.json
  src/places/placesController.js
  src/places/placesDao.js
  src/places/placesRouter.js
  src/places/placesService.js
  src/reviews/reviewsController.js
  src/reviews/reviewsDao.js
  src/reviews/reviewsRouter.js
  src/reviews/reviewsService.js
Labels: enhancement

#56 Update: user put -> patch
  src/user/userController.js
  src/user/userProvider.js
  src/user/userRouter.js
Labels: enhancement

#55 Update: /records, multer
  config/baseResponeStatus.js
  index.js
  src/records/recordsController.js
  src/records/recordsDao.js
  src/records/recordsProvider.js
  src/records/recordsRouter.js
  src/records/recordsService.js
  src/user/userController.js
  src/user/userRouter.js
Labels: enhancement

#59 Feat: user mypage
  config/express.js
  src/user/userController.js
  src/user/userDao.js
  src/user/userRouter.js
  src/user/userService.js
Labels: enhancement

#61 Feat: 60 - PUT /records/:recordId, DELETE /records/:recordId/images
  src/records/recordsController.js
  src/records/recordsDao.js
  src/records/recordsProvider.js
  src/records/recordsRouter.js
Labels: enhancement

#70 Feat: 69 PATCH /records/comment/:commentId
  config/baseResponeStatus.js
  src/records/recordsController.js
  src/records/recordsDao.js
  src/records/recordsProvider.js
  src/records/recordsRouter.js
  src/records/recordsService.js
Labels: ✨Feature

#75 Feature/73 update search
  package.json
  src/places/placesController.js
  src/places/placesDao.js
  src/places/placesService.js
Labels: ✨ Feature, 🔧 Update

#72 Feat/12 auth sign in 다시
  config/express.js
  package.json
  src/Activity/activityRouter.js
  src/activities/activitiesController.js
  src/activities/activitiesDao.js
  src/activities/activitiesProvider.js
  src/activities/activitiesRouter.js
  src/auth/authController.js
  src/auth/authDao.js
  src/auth/authProvider.js
  src/auth/authRouter.js
  src/auth/authService.js
Labels: ✨ Feature

#71 Feauter/65 user follow
  config/baseResponeStatus.js
  src/user/userController.js
  src/user/userDao.js
  src/user/userProvider.js
  src/user/userRouter.js
  src/user/userService.js
Labels: ✨ Feature

#77 Fix records, users service-provider
  config/express.js
  src/records/recordsController.js
  src/records/recordsProvider.js
  src/records/recordsService.js
  src/user/userController.js
  src/user/userRouter.js
  src/users/usersController.js
  src/users/usersDao.js
  src/users/usersProvider.js
  src/users/usersRouter.js
  src/users/usersService.js
Labels: 🐛 Bug

#83 인증 미들웨어 추가 후 사용자 데이터 불러오기
  config/baseResponeStatus.js
  config/middlewares.js
  src/places/placesController.js
  src/places/placesRouter.js
  src/records/recordsController.js
  src/reviews/reviewsController.js
  src/reviews/reviewsDao.js
  src/reviews/reviewsProvider.js
  src/reviews/reviewsService.js
  src/users/usersController.js
Labels: ✨ Feature, 🔧 Update

#88 Docs: build badge 추가
  README.md
Labels: 📑 Documentation

#85 Feature/84 delete following 친구 삭제 기능 추가
  config/baseResponeStatus.js
  config/logger.js
  src/users/usersController.js
  src/users/usersDao.js
  src/users/usersProvider.js
  src/users/usersRouter.js
  src/users/usersService.js
Labels: ✨ Feature, 🔧 Update

#87 회원가입, 로그인 로직 및 사소한 부분 보안
  config/baseResponeStatus.js
  config/s3.js
  src/auth/authController.js
  src/auth/authDao.js
  src/auth/authProvider.js
  src/auth/authService.js
  src/reviews/reviewsService.js
  src/users/usersController.js
  src/users/usersRouter.js
Labels: ✨ Feature, 🔧 Update

#89 Feat/ 78 - DELETE /records/:recordId/images 수정
  config/s3.js
  src/records/recordsController.js
  src/records/recordsDao.js
  src/records/recordsService.js
Labels: ✨ Feature
